{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arcanc.pulselib",
    "module": "pulselib-neoforge",
    "version": "26.2-1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.3.jar",
          "url": "pulselib-neoforge-26.2-1.1.3.jar",
          "size": 3271566,
          "sha512": "58ae4479bc6032508620771c9642f0dca8cf742cb42dc099c6b0fcdb0138de7888fae7d9041ad03b926931bdbc4de599cbf9bf3f8616e48114ffed72a8824264",
          "sha256": "f0535778d1d12de40b1c8a1ddf87be5ecf0228cdffe7796c9825344bdc7346f9",
          "sha1": "8936e03b23198c2981105c06002f2a14f0f56b45",
          "md5": "c44c8b8ea76c182a5ddff9419defe062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.javagl",
          "module": "jgltf-model",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "de.javagl",
          "module": "jgltf-impl-v1",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "de.javagl",
          "module": "jgltf-impl-v2",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.3.jar",
          "url": "pulselib-neoforge-26.2-1.1.3.jar",
          "size": 3271566,
          "sha512": "58ae4479bc6032508620771c9642f0dca8cf742cb42dc099c6b0fcdb0138de7888fae7d9041ad03b926931bdbc4de599cbf9bf3f8616e48114ffed72a8824264",
          "sha256": "f0535778d1d12de40b1c8a1ddf87be5ecf0228cdffe7796c9825344bdc7346f9",
          "sha1": "8936e03b23198c2981105c06002f2a14f0f56b45",
          "md5": "c44c8b8ea76c182a5ddff9419defe062"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.3-sources.jar",
          "url": "pulselib-neoforge-26.2-1.1.3-sources.jar",
          "size": 718153,
          "sha512": "37960fec087728b895c7ef5007b057f89a6996bf0850fb338b772dfc3ebd1ddbe433b6e99e765ed5d64ab5e476afdcb944da83fdf3ce4bae17ee84a30c478af0",
          "sha256": "accc0fcb9b50e333936f93a8ec6d3b7878000e935cab68f78e7017ea9f67853f",
          "sha1": "552ce76321b40781aa822b02901deae09ff638b3",
          "md5": "b093ccbfbcd5362847b140ae915eda6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.3-javadoc.jar",
          "url": "pulselib-neoforge-26.2-1.1.3-javadoc.jar",
          "size": 5291632,
          "sha512": "3d7df160b66cc7991a2e4de8e3a7db2420ea1ee31058b4dd7c08f4038e2b30c9035bb7c392d6d4bb71d755306141c2077affb6b39e05d911bbb8e1e84679341f",
          "sha256": "9457884a51c2f462df7d44cfc6a0f95c299b65ff830e6a583c3b2190d1158880",
          "sha1": "bedc26be0b690fa2636a903a88999b90030e02c5",
          "md5": "52a9184da9d5a2448fc47ea0eb5a909e"
        }
      ]
    }
  ]
}
