{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arcanc.pulselib",
    "module": "pulselib-neoforge",
    "version": "26.2-1.1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.4.2.jar",
          "url": "pulselib-neoforge-26.2-1.1.4.2.jar",
          "size": 3292192,
          "sha512": "299e41e0002a3b2d35576b31760fc78030a057bf6709fea8f7f83e9564cfef5f574f079570b37ff05d104d371248e287540df0f7ab1f6cb41fcced3c1968fc41",
          "sha256": "5450c340ced5e69fedb9da2c5f1075b9a85686cf976c7cff3f41b557daed696f",
          "sha1": "efea7c98c55a16100e8defd1df299cf82dde6474",
          "md5": "69f281f44facc57d7a8ea3d8df837526"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.javagl",
          "module": "jgltf-model",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "de.javagl",
          "module": "jgltf-impl-v1",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "de.javagl",
          "module": "jgltf-impl-v2",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.4.2.jar",
          "url": "pulselib-neoforge-26.2-1.1.4.2.jar",
          "size": 3292192,
          "sha512": "299e41e0002a3b2d35576b31760fc78030a057bf6709fea8f7f83e9564cfef5f574f079570b37ff05d104d371248e287540df0f7ab1f6cb41fcced3c1968fc41",
          "sha256": "5450c340ced5e69fedb9da2c5f1075b9a85686cf976c7cff3f41b557daed696f",
          "sha1": "efea7c98c55a16100e8defd1df299cf82dde6474",
          "md5": "69f281f44facc57d7a8ea3d8df837526"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.4.2-sources.jar",
          "url": "pulselib-neoforge-26.2-1.1.4.2-sources.jar",
          "size": 727873,
          "sha512": "4fd93df5a2a5e9303c1fae9ae17fc9ab157e1ea3884e09395a4e7be47ec39a1d10beb0dce7fc0dc478037035c50fcc53bdf6174f4e4f4b25b1a57fb69a9ff345",
          "sha256": "d1960f71953b583c36e55a3b67f81471c4de6f04ffe37d61c5fda3e5a0ebd323",
          "sha1": "bfb9f2aac1a28aaab565ef5c1c1c8848623ba506",
          "md5": "3f2dc16d6f4d05eebaea775a97dd4f8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.2-1.1.4.2-javadoc.jar",
          "url": "pulselib-neoforge-26.2-1.1.4.2-javadoc.jar",
          "size": 5309298,
          "sha512": "86ff55fd0b1fd4fe2c49194dbf32509609567ed2487c4de7b9dde6878e856c19dff01dada3e9d8a85c17351cfe3e7728569d4002bdd88ee01918ae2fc792d326",
          "sha256": "8a3998289a5ecfbc2130e924d9805c45ac355e03cbf4b707ac5cb79ec8132ee7",
          "sha1": "e844c1d795800900a5f46a70282093904c9f512b",
          "md5": "804f19863fe6c2c7e045e4e14c459ae8"
        }
      ]
    }
  ]
}
