{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arcanc.pulselib",
    "module": "pulselib-neoforge",
    "version": "26.1.2-1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.1.2-1.1.3.jar",
          "url": "pulselib-neoforge-26.1.2-1.1.3.jar",
          "size": 3279470,
          "sha512": "884e811f38884aef1260340a44384ea9739f3eb57f3fb3f2e7de36cbd2f32ac6756e851591cdab3e068facd98512f4ef028c33166a9533c9160d06bf61d8e851",
          "sha256": "949d0b433a8ad1630421919a0cc88465d53670cca4e6bd7ca830e729e328e49b",
          "sha1": "07f10751c2988ff0a43adbb525d3bc8ad998fbe0",
          "md5": "94ae7041764ef7551944a06996c0e0e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.javagl",
          "module": "jgltf-model",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "de.javagl",
          "module": "jgltf-impl-v1",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "de.javagl",
          "module": "jgltf-impl-v2",
          "version": {
            "strictly": "[2.0,3.0)",
            "requires": "[2.0,3.0)",
            "prefers": "2.0.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.10, 2.20)",
            "requires": "[2.10, 2.20)",
            "prefers": "2.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "pulselib-neoforge-26.1.2-1.1.3.jar",
          "url": "pulselib-neoforge-26.1.2-1.1.3.jar",
          "size": 3279470,
          "sha512": "884e811f38884aef1260340a44384ea9739f3eb57f3fb3f2e7de36cbd2f32ac6756e851591cdab3e068facd98512f4ef028c33166a9533c9160d06bf61d8e851",
          "sha256": "949d0b433a8ad1630421919a0cc88465d53670cca4e6bd7ca830e729e328e49b",
          "sha1": "07f10751c2988ff0a43adbb525d3bc8ad998fbe0",
          "md5": "94ae7041764ef7551944a06996c0e0e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.1.2-1.1.3-sources.jar",
          "url": "pulselib-neoforge-26.1.2-1.1.3-sources.jar",
          "size": 717393,
          "sha512": "4e513d955c97d190296c9a30c078fb5f4ce41f37f8a084226b955cb9467affe3fe5ce93041b7b3e8490a1126e6e87ecefec7e234c73ef9586d98d125e1556ed0",
          "sha256": "4f6fb885e70a3fc7dfe0321271fb62c8b10d91f6bccb3e54e84c23ac22c1e26b",
          "sha1": "645991d750487b67288720f9ed6f020955ea6140",
          "md5": "abbcd6993ed977be335e8745dac3846d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pulselib-neoforge-26.1.2-1.1.3-javadoc.jar",
          "url": "pulselib-neoforge-26.1.2-1.1.3-javadoc.jar",
          "size": 5318063,
          "sha512": "860c9fec06d790003ad72804dda319c82d4e38d8c797131c78777d15755a68291fb74ae18dcb9f1bd3eef33130b6d9a39e987b2b0ed9d2ff8cce35f9c9a752aa",
          "sha256": "79627aada78e88cb6c5fb71fe37c4a99326e44fcf7e35e42969ba6da7b4f1726",
          "sha1": "a6617b7a530480da5680d5d36a38683682cccae2",
          "md5": "2e8ecf91b66a62496377d193e6ceb679"
        }
      ]
    }
  ]
}
